<h2>1. Load The Dataset</h2>
<h3>1.1 Import Necessary libaries and load the dataset.</h3>

In [53]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib import colors

In [54]:
# Load the Stack Overflow survey data
df = pd.read_csv("survey_data.csv")

# Display the first few rows
df.head()

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
0,2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
1,3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
2,10,I am a developer by profession,35-44 years old,"Independent contractor, freelancer, or self-em...",Remote,Apples,Bootstrapping a business,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",On the job training;Other online resources (e....,Technical documentation;Blogs;Written Tutorial...,...,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
3,11,"I used to be a developer by profession, but no...",35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Books;Written Tutorial...,...,25.0,10.0,0.0,15.0,0.0,0.0,Appropriate in length,Easy,NaN,8.0
4,12,I am a developer by profession,45-54 years old,"Employed, full-time",In-person,Apples,Hobby;School or academic work,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Books / Physical media;School (i.e., Universit...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,NaN,NaN

In [55]:
print(df.dtypes)

ResponseId               int64
MainBranch              object
Age                     object
Employment              object
RemoteWork              object
                        ...
JobSatPoints_11        float64
SurveyLength            object
SurveyEase              object
ConvertedCompYearly    float64
JobSat                 float64
Length: 114, dtype: object

<h3>1.2 Remove Duplicates</h3>

In [56]:
# Find all duplicate occurrences
all_duplicate_occurrences = df[df.duplicated(keep=False)]
all_duplicate_occurrences

Empty DataFrame
Columns: [ResponseId, MainBranch, Age, Employment, RemoteWork, Check, CodingActivities, EdLevel, LearnCode, LearnCodeOnline, TechDoc, YearsCode, YearsCodePro, DevType, OrgSize, PurchaseInfluence, BuyNewTool, BuildvsBuy, TechEndorse, Country, Currency, CompTotal, LanguageHaveWorkedWith, LanguageWantToWorkWith, LanguageAdmired, DatabaseHaveWorkedWith, DatabaseWantToWorkWith, DatabaseAdmired, PlatformHaveWorkedWith, PlatformWantToWorkWith, PlatformAdmired, WebframeHaveWorkedWith, WebframeWantToWorkWith, WebframeAdmired, EmbeddedHaveWorkedWith, EmbeddedWantToWorkWith, EmbeddedAdmired, MiscTechHaveWorkedWith, MiscTechWantToWorkWith, MiscTechAdmired, ToolsTechHaveWorkedWith, ToolsTechWantToWorkWith, ToolsTechAdmired, NEWCollabToolsHaveWorkedWith, NEWCollabToolsWantToWorkWith, NEWCollabToolsAdmired, OpSysPersonal use, OpSysProfessional use, OfficeStackAsyncHaveWorkedWith, OfficeStackAsyncWantToWorkWith, OfficeStackAsyncAdmired, OfficeStackSyncHaveWorkedWith, OfficeStackSyncWantToWorkWith, OfficeStackSyncAdmired, AISearchDevHaveWorkedWith, AISearchDevWantToWorkWith, AISearchDevAdmired, NEWSOSites, SOVisitFreq, SOAccount, SOPartFreq, SOHow, SOComm, AISelect, AISent, AIBen, AIAcc, AIComplex, AIToolCurrently Using, AIToolInterested in Using, AIToolNot interested in Using, AINextMuch more integrated, AINextNo change, AINextMore integrated, AINextLess integrated, AINextMuch less integrated, AIThreat, AIEthics, AIChallenges, TBranch, ICorPM, WorkExp, Knowledge_1, Knowledge_2, Knowledge_3, Knowledge_4, Knowledge_5, Knowledge_6, Knowledge_7, Knowledge_8, Knowledge_9, Frequency_1, Frequency_2, Frequency_3, TimeSearching, TimeAnswering, Frustration, ProfessionalTech, ProfessionalCloud, ProfessionalQuestion, ...]
Index: []

[0 rows x 114 columns]

<h3>1.3 Filter Wanted Columns</h3>

In [57]:
columns = ['LanguageHaveWorkedWith', 'DatabaseHaveWorkedWith', 'PlatformHaveWorkedWith', 'WebframeHaveWorkedWith', 
           'LanguageWantToWorkWith', 'DatabaseWantToWorkWith', 'PlatformWantToWorkWith', 'WebframeWantToWorkWith',
           'Country', 'Age', 'EdLevel']
df_sub = df[columns].copy()

In [58]:
#Find All Null Values Rows in df
df_sub.isnull().any()

LanguageHaveWorkedWith    False
DatabaseHaveWorkedWith    False
PlatformHaveWorkedWith    False
WebframeHaveWorkedWith    False
LanguageWantToWorkWith    False
DatabaseWantToWorkWith    False
PlatformWantToWorkWith    False
WebframeWantToWorkWith    False
Country                   False
Age                       False
EdLevel                   False
dtype: bool

In [59]:
df_sub['Age'].value_counts()

Age
25-34 years old       7788
35-44 years old       5149
18-24 years old       2988
45-54 years old       2053
55-64 years old        632
Under 18 years old     136
65 years or older       75
Prefer not to say       24
Name: count, dtype: int64

In [60]:
df_sub['EdLevel'].value_counts()

EdLevel
Bachelor’s degree (B.A., B.S., B.Eng., etc.)                                          8629
Master’s degree (M.A., M.S., M.Eng., MBA, etc.)                                       5000
Some college/university study without earning a degree                                2456
Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)    1143
Professional degree (JD, MD, Ph.D, Ed.D, etc.)                                         661
Associate degree (A.A., A.S., etc.)                                                    634
Something else                                                                         190
Primary/elementary school                                                              132
Name: count, dtype: int64

In [61]:
df_sub['Country'].value_counts()

Country
United States of America                                3441
Germany                                                 1339
India                                                   1316
United Kingdom of Great Britain and Northern Ireland    1053
Ukraine                                                  931
                                                        ...
Brunei Darussalam                                          1
Guyana                                                     1
Mali                                                       1
Cape Verde                                                 1
Barbados                                                   1
Name: count, Length: 161, dtype: int64

<h3>1.4 Wrangle Data for Dashboard</h3>
<h4>1.4.1 Standardize 'EdLevel'</h4>

In [62]:
#Make EdLevel to Samll Case
df_sub['EdLevel'] = df_sub['EdLevel'].str.lower().str.strip()

#Replace instances
df_sub['EdLevel'] = df_sub['EdLevel'].replace('primary/elementary school', 'No Degree')
df_sub['EdLevel'] = df_sub['EdLevel'].replace("bachelor’s degree (b.a., b.s., b.eng., etc.)", "Bachelor's Degree")
df_sub['EdLevel'] = df_sub['EdLevel'].replace("master’s degree (m.a., m.s., m.eng., mba, etc.)", "Graduate Degree")
df_sub['EdLevel'] = df_sub['EdLevel'].replace("some college/university study without earning a degree", 'High School Degree')
df_sub['EdLevel'] = df_sub['EdLevel'].replace("secondary school (e.g. american high school, german realschule or gymnasium, etc.)", 'High School Degree')
df_sub['EdLevel'] = df_sub['EdLevel'].replace("professional degree (jd, md, ph.d, ed.d, etc.)", 'Graduate Degree')
df_sub['EdLevel'] = df_sub['EdLevel'].replace("associate degree (a.a., a.s., etc.)", 'Associate Degree')
df_sub['EdLevel'] = df_sub['EdLevel'].replace("something else", 'NA')
df_sub['EdLevel'] = df_sub['EdLevel'].fillna('NA')

In [63]:
df_sub['EdLevel'].value_counts()

EdLevel
Bachelor's Degree     8629
Graduate Degree       5661
High School Degree    3599
Associate Degree       634
NA                     190
No Degree              132
Name: count, dtype: int64

<h4>1.4.2 Clean 'Country' Column</h4>
<p>Use Webscraping methods to crawl valid country list. Check user input against them to find spelling errors, and input errors.</p>

In [64]:
#Find Spelling Errors/Input Errors

#import libraries for WebScraping
from bs4 import BeautifulSoup # this module helps in web scrapping.
import requests

#Scraping Country List form Worldometers.com
url = "https://www.worldometers.info/geography/alphabetical-list-of-countries/"
response = requests.get(url)
html_content = response.text

soup = BeautifulSoup(html_content, "html.parser")
#Find all <table> tags
tables = soup.find_all("table")
table = tables[0]

country = []
for row in table.find('tbody').find_all('tr'): # Assuming a tbody
    cols = row.find_all('td')
    country.append(cols[1].get_text().strip()) #Country is 2nd Column in Table

In [65]:
#Replace Some Country for Standardization
country[38] = 'Congo' # From Congo (Congo-Brazzaville) 
country[44] = 'Czech Republic' #From 'Czechia (Czech Republic)'
country[56] = 'Eswatini' #From 'Eswatini (fmr. ""Swaziland"")'
country[118] = 'Myanmar' #From 'Myanmar (formerly Burma)'
country[133] = 'Palestine' #From Palestine State

#Append Country that are not in the List, but in the survey
country.append('Hong Kong (S.A.R.)')
country.append('Taiwan')
country.append('Isle of Man')
country.append('Kosovo')
country.append("Côte d'Ivoire")

#Save Country List in CSV File for future use too
pd.Series(country).to_csv('countries.csv', index=False)

In [66]:
# Check if values in 'col1' are in my_list
not_valid = ~df_sub['Country'].isin(country)
df_sub[not_valid]['Country'].unique()

array(['United Kingdom of Great Britain and Northern Ireland',
       'Republic of North Macedonia', 'United Republic of Tanzania',
       'Russian Federation', 'Viet Nam',
       'Venezuela, Bolivarian Republic of...',
       'Iran, Islamic Republic of...', 'Republic of Korea',
       'Syrian Arab Republic', 'Nomadic', 'Republic of Moldova',
       'Congo, Republic of the...', 'Brunei Darussalam', 'Cape Verde'],
      dtype=object)

In [67]:
#Replace Dataset for different names refering to same country
#Standardization Purpose
df_sub['Country'] = df_sub['Country'].replace('United Kingdom of Great Britain and Northern Ireland', 'United Kingdom')
df_sub['Country'] = df_sub['Country'].replace('Republic of North Macedonia', 'North Macedonia')
df_sub['Country'] = df_sub['Country'].replace('Russian Federation', 'Russia')
df_sub['Country'] = df_sub['Country'].replace('Viet Nam', 'Vietnam')
df_sub['Country'] = df_sub['Country'].replace('Venezuela, Bolivarian Republic of...', 'Venezuela')
df_sub['Country'] = df_sub['Country'].replace('United Republic of Tanzania', 'Tanzania')
df_sub['Country'] = df_sub['Country'].replace('Iran, Islamic Republic of...', 'Iran')
df_sub['Country'] = df_sub['Country'].replace('Republic of Korea', 'South Korea')
df_sub['Country'] = df_sub['Country'].replace('Syrian Arab Republic', 'Syria')
df_sub['Country'] = df_sub['Country'].replace('Republic of Moldova', 'Moldova')
df_sub['Country'] = df_sub['Country'].replace('Congo, Republic of the...', 'Congo')
df_sub['Country'] = df_sub['Country'].replace('Brunei Darussalam', 'Brunei')
df_sub['Country'] = df_sub['Country'].replace('Cape Verde', 'Cabo Verde')

In [68]:
#Some people input 'Nomadic' for country column
#Check how many respondents with Nomadic value
df_sub.loc[df_sub['Country'] == 'Nomadic']

#There is six records,
#I'll leave as it is for now

,LanguageHaveWorkedWith,DatabaseHaveWorkedWith,PlatformHaveWorkedWith,WebframeHaveWorkedWith,LanguageWantToWorkWith,DatabaseWantToWorkWith,PlatformWantToWorkWith,WebframeWantToWorkWith,Country,Age,EdLevel
2387,Bash/Shell (all shells);HTML/CSS;JavaScript;Py...,MariaDB;MongoDB;MySQL;Neo4J;PostgreSQL;SQLite,Amazon Web Services (AWS);Digital Ocean;Vultr,Flask;Node.js;Play Framework;React,Elixir;Erlang;HTML/CSS;Python;TypeScript,PostgreSQL,Amazon Web Services (AWS);Digital Ocean;Vultr,Flask;Node.js;Play Framework;React,Nomadic,25-34 years old,Graduate Degree
4525,Elixir;JavaScript;Swift;TypeScript,PostgreSQL;Supabase,Amazon Web Services (AWS);Fly.io,Node.js;Phoenix;React,Elixir;Kotlin;OCaml;Swift,PostgreSQL;Supabase,Amazon Web Services (AWS);Fly.io,Phoenix,Nomadic,35-44 years old,Graduate Degree
11440,Ada;Apex;Assembly;Bash/Shell (all shells);C;C#...,BigQuery;Cassandra;Clickhouse;Cloud Firestore;...,Alibaba Cloud;Amazon Web Services (AWS);Cloudf...,Angular;AngularJS;ASP.NET;ASP.NET CORE;Astro;B...,Ada;Apex;Assembly;Bash/Shell (all shells);C;C#...,BigQuery;Cassandra;Clickhouse;Cloud Firestore;...,Alibaba Cloud;Amazon Web Services (AWS);Cloudf...,Angular;AngularJS;ASP.NET;ASP.NET CORE;Astro;B...,Nomadic,35-44 years old,NA
12777,Assembly;C;C#;C++;Cobol;Delphi;Fortran;Java;Ja...,Couch DB;Elasticsearch;IBM DB2;MariaDB;Microso...,Cloudflare;Digital Ocean;Microsoft Azure;OpenS...,ASP.NET;ASP.NET CORE;FastAPI;Flask;Node.js;Rub...,Bash/Shell (all shells);Java;JavaScript;Python...,MariaDB;MySQL;SQLite,Microsoft Azure;OpenStack,FastAPI;Flask;Node.js;WordPress,Nomadic,45-54 years old,Graduate Degree
13061,Bash/Shell (all shells);C;C#;C++;HTML/CSS;Java...,MariaDB;Microsoft SQL Server;MySQL;PostgreSQL,Google Cloud,ASP.NET;ASP.NET CORE;Blazor;Django;Flask;jQuer...,Bash/Shell (all shells);C;C#;HTML/CSS;Java;Jav...,MariaDB;Microsoft SQL Server;MySQL;PostgreSQL;...,Google Cloud,ASP.NET;ASP.NET CORE;Blazor;Django;Express;Fla...,Nomadic,18-24 years old,Bachelor's Degree
16336,Bash/Shell (all shells);Delphi;HTML/CSS;JavaSc...,Firebird;MariaDB;Microsoft SQL Server;MySQL,Amazon Web Services (AWS),jQuery;Node.js,Bash/Shell (all shells);Delphi;HTML/CSS;JavaSc...,Firebird;MariaDB;MySQL;PostgreSQL,Amazon Web Services (AWS),jQuery;Node.js,Nomadic,35-44 years old,Bachelor's Degree

In [69]:
#Saving Cleaned Dataset for Further Analysis, and Visualization
df_sub.to_csv('survey_data-v1.csv', index=False)

<h4>1.4.3 Data Wrangling</h4>

In [91]:
axis = ['Language', 'Database', 'Platform', 'Webframe']


for ax in axis:
    #To seperate data to multiple columns, use one hot encoding method
    dummies = df_sub[f'{ax}HaveWorkedWith'].str.get_dummies(sep=';')

    #Get Respondent Count for Each Category and save it to Dataframe
    lnTrend = dummies.sum().transpose().to_frame()
    
    dummies = df_sub[f'{ax}WantToWorkWith'].str.get_dummies(sep=';')
    lnTrend['InterestedUsers'] = dummies.sum().transpose().to_frame()
    lnTrend = lnTrend.reset_index()
    lnTrend.columns = ['Name', 'ExperienceUsers', 'InterestedUsers']

    #Save into .csv for usage in Dashboarding s/w
    lnTrend.to_csv(f'{ax}Trend.csv', index=False)